### ISSUE TITLE
Plugin Not Working

### ISSUE THREAD

**Issue by Lorenzo0111** [help-chat/BukkitForcedHosts#1]
The plugin is not working on my server.
It works only with he numerical ip.

**Configuration:** https://paste.helpch.at/enukiveroz.pl
**DNS Configuration:**
![](https://gyazo.com/487804941b02a5814fa00a4718573cb0.png)
![](https://gyazo.com/4e6b72cd514ccb8a32c4ec64f98fadf5.png)

**Server Information:**  https://paste.helpch.at/ukuhebofiq.css

**Comment by PiggyPiglet** [comment]
I was unable to reproduce this issue using the same version of paper as you, java 8_275 (adoptopenjdk, hotspot) on kde neon user edition 5.21 on localhost, with the following hosts.yml:
```
config-version: 1
test-piggypiglet-me:
  commands:
    - "tellraw %s {\"text\":\"Hello\"}"
```

**Comment by Lorenzo0111** [comment]
Ok, maybe it is a problem of the host.
Thanks.
